# goal
int32 placement_index        # 놓일 타일 위치
float32 search_force         # 접촉 탐색 힘
float32 press_force          # 실제 압착 힘
float32 hold_time            # 압착 유지 시간
float32 target_press_depth   # 목표 압착 깊이
---
# result
bool success
float32 press_depth #최종 압착깊이
string message

---
# feedback
string state # 현재 단계
float32 fx
float32 fy
float32 fz
float32 tx
float32 ty
float32 tz
float32 pressed_depth # 현재까지 눌린 깊이 
float32 progress